version: '3.8'
services:
  db:
    build: ./app/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: harish
      MYSQL_PASSWORD: harish1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./app
    environment:
      DB_USER: harish
      DB_PASSWORD: harish1234
      DB_HOST: db
      DB_NAME: mydb
    ports:
      - "5000:5000"
    depends_on:
      - db
    working_dir: /app/Application
    command: ["python", "application.py"]
volumes:
  db_data:
